name: Generate Android upload keystore

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore upload-keystore.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -alias "${{ secrets.KEY_ALIAS }}" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Gymnazium Arcus, OU=IT, O=Gymnazium Arcus, L=Prague, S=CZ, C=CZ"

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-keystore
          path: upload-keystore.jks
